# Generated by Django 4.2.2 on 2023-06-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('frontpix', models.ImageField(upload_to='frontpix')),
                ('backpix', models.ImageField(upload_to='backpix')),
            ],
        ),
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='logo')),
                ('banner', models.ImageField(upload_to='banner')),
                ('copyright', models.IntegerField()),
            ],
        ),
    ]
