# Generated by Django 4.1.9 on 2023-06-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='last_name',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
