# Generated by Django 4.2.2 on 2023-06-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_register_address_register_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='full_names',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
